# Generated by Django 4.2.8 on 2024-01-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('access', models.TextField(blank=True, null=True)),
                ('business_hours', models.TextField(blank=True, null=True)),
                ('thumbnail_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
